service: cowin-alert
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-south-1
  memorySize: 128
  timeout: 10
  lambdaHashingVersion: 20201221

functions:
  cowinMailer:
    handler: handler.mailer
    environment:
      GMAIL_PASS: ${ssm:/gmailPass}
    events:
      - schedule:
          rate: rate(30 minutes)